// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzelwlabsgdhjfbcrbyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6ZWx3bGFic2dkaGpmYmNyYnl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2NTE3NTcsImV4cCI6MjA1ODIyNzc1N30.6SqsqGPwyadycTYYLlmsJ4XVDrEGQnFVZFfUYYpC9wo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);